version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    volumes:
      - ./sql_sqripts:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: "cism"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"