version: '3'

services:
  krakend_ce:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8075:8070"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    container_name: kraken
    depends_on:
      - doc-app
      - print-app
      - micro-1-app
      - micro-2-app
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:1
    ports:
      - "16686:16686"
      - "14268:14268"
  doc-app:
    build: ./document_api
    container_name: doc_cont
    ports:
      - "8010:8010"
  print-app:
    build: ./printer_api
    container_name: print_cont
    ports:
      - "8011:8011"
  micro-1-app:
    build: ./micro_1_api
    container_name: micro_1_cont
    ports:
      - "8012:8012"
  micro-2-app:
    build: ./micro_2_api
    container_name: micro_2_cont
    ports:
      - "8013:8013"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - '8085:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev