version: '3'

services:
  krakend_ce:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8075:8070"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    container_name: kraken
    depends_on:
      - doc-app
      - print-app
  doc-app:
    build: ./document_api
    container_name: doc_cont
    ports:
      - "8010:8010"

  print-app:
    build: ./printer_api
    container_name: print_cont
    ports:
      - "8011:8011"